CREATE DATABASE IF NOT EXISTS `javaweb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `javaweb`;

CREATE TABLE IF NOT EXISTS `inputfile` (
  `col1` VARCHAR(45) NOT NULL,
  `col2` VARCHAR(45) NOT NULL,
  `col3` VARCHAR(45) NOT NULL,
  `col4` VARCHAR(45) NOT NULL,
  `col5` VARCHAR(45) NOT NULL,
  `col6` VARCHAR(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;